name: Hello, World!
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Hello, World!"
        echo "Hello, Github Action"
